
args = { 
    "BUFFER_SIZE":int(1e6),
    "BATCH_SIZE":1024,  
    "GAMMA":0.99,
    "TAU":2e-3,
    "LR_ACTOR":1e-3,
    "LR_CRITIC":1.1e-3,
    "WEIGHT_DECAY":0.0001,
    "UPDATE_EVERY":5,
    "EXPLORE_NOISE":0.05,
    "FC1_UNITS":1024,
    "FC2_UNITS":10240,
    "FC3_UNITS":1024,
    "seed":0,
    "state_size":384,
    "action_size":87,
    "num_agents":2,
    "device":device,
    'mcritic_path':'/home/ubuntu/chessy/checkpoint_mCritic.pth',
    'agent_p0_path':'/home/ubuntu/chessy/checkpoint_p0.pth',
    'agent_p1_path':'/home/ubuntu/chessy/checkpoint_p1.pth',
    'action_ids': action_ids,
    'action_id_dict': action_id_dict,
    'id_action_dict': id_action_dict,
    'numeric_names' : numeric_names,
    'initial_state'  : initial_state,
    
}
